### ISSUE TITLE
Make module support flipping between single instance and multi-instance mode

### ISSUE THREAD

**Issue by lukebigum** [LMAX-Exchange/puppet-linuxptp#7]
A proposal for you, @gerhard-tinned.  When I wrote this I was using multiple instances of ptp4l on a machine and I specifically wrote it to not handle running ptp4l / phy2sys in the "normal" way (hence all your PRs).

If I were to branch to version 2.x and refactor this module so that you could more easily flip between my multi-instance and the standard Red Hat single instance scripts, would that be easier for you? It would probably look a bit like [LMAX-Exchange/ptpd](https://github.com/LMAX-Exchange/puppet-ptpd/tree/master/manifests) works right now. There would be a default parameter like so:

`class { 'linuxptp': single_instance => true }`

And the multi-instance stuff you'd have to do this:

`class { 'linuxptp': single_instance => false }
linuxptp::ptp4l { 'eth0': }`

So by default everything would behave like the RPM packages expect (no different location for config files).

Would that be of interest?

**Comment by gerhard-tinned** [comment]
In general, I would like this. I have a very short time frame to get everything running. Not sure if that would work for me. 

Besides, I got everything I need running so far under RHEL7.

**Comment by lukebigum** [comment]
Alright, cool. If I get some free time I'll make a new branch of this module and do a big refactor.  You are the only one in the world whom I know uses this module. I don't use ptp4l any more, I use the latest Alpha branches of [PTPD](https://github.com/lukebigum/ptpd).

**Comment by gerhard-tinned** [comment]
In that case, I am very thankful for your support with the module. 

Would you start re-factor the module in a feature brunch? So we could use it as it is until we can test the feature branch and then switch over coordinated? That would be great. 

For us to use the re-factored class, the changes would be needed very very soon (not to stress you). This is because of our procedures. What would be your time frame to do this?

**Comment by lukebigum** [comment]
Try this branch:

https://github.com/LMAX-Exchange/puppet-linuxptp/tree/2.0/

It looks ok from the point of view of the unit tests.

Some of the parameters needed to be renamed, the Camel case has gone to Snake case to be future parser compatible, eg: logMinPdelayReqInterval is now log_min_pdelay_req_interval.

**Comment by gerhard-tinned** [comment]
Thanks for the quick rewrite. We have tested the 2.0 branch and had to make a small change (see PR #8). Besides this tiny thing, it works great. Thaks a lot!!

**Comment by lukebigum** [comment]
Merged.  If you're happy with 2.0 I'll merge that into Master.

**Comment by gerhard-tinned** [comment]
Wow, great. So far it works nicely. Go ahead and merge it. 

Would be great if there would be a release tag to use as reference.

**Comment by lukebigum** [comment]
Done, tagged 0.1.0 and 2.0.

**Comment by gerhard-tinned** [comment]
Awesome thanks. 

May I ask out of curiosity why you changed to ptpd?

BTW, it would be safe to state its compatibility to RHEL / CentOS 7 as this is what we use it with. :)
